#!/usr/bin/env python3
"""
m2_build.py - single build path for Milestone 2 (PHYSICS_BOOT) artifacts.

Every build starts from source. Nothing is reused from a previous run, so a
gate can never pass against a stale object or binary.

Canonical artifacts (built in the repository root):
  physics.bin      <- physics.s vector_table.s memory_alloc.s capability.s
  physics_pin.inc  <- SHA-256 of that physics.bin (the only copy of the pin)
  atlas_m2.bin     <- atlas_m2.s + sha256_clean.c, pinning physics.bin

Seam 2 variants (test-only physics images and hostile Atlas descriptors) are
built into their own directories under build/ and never touch the canonical
files. atlas_m2.s picks up physics_pin.inc from the assembler's working
directory, so each variant directory carries its own pin.
"""

import hashlib
import os
import subprocess

CC = "aarch64-linux-gnu-gcc"
LD = "aarch64-linux-gnu-ld"
OBJCOPY = "aarch64-linux-gnu-objcopy"

PHYSICS_MODULES = ["vector_table.s", "memory_alloc.s", "capability.s"]


def _run(cmd, cwd=None):
    subprocess.run(cmd, check=True, cwd=cwd)


def assemble(src, obj, defsyms=None, cwd=None):
    cmd = [CC, "-c", "-nostdlib", "-ffreestanding"]
    for name, value in (defsyms or {}).items():
        cmd.append(f"-Wa,--defsym,{name}={value}")
    cmd += [os.path.abspath(src), "-o", os.path.abspath(obj)]
    _run(cmd, cwd=cwd)


def sha256_file(path):
    with open(path, "rb") as f:
        return hashlib.sha256(f.read()).hexdigest()


def build_physics(out_dir, repo=".", entry_source=None):
    """Build physics.elf/physics.bin into out_dir. entry_source replaces
    physics.s (Seam 2 test images); the other modules are always the
    canonical sources."""
    repo = os.path.abspath(repo)
    os.makedirs(out_dir, exist_ok=True)
    entry_source = entry_source or os.path.join(repo, "physics.s")
    objs = []
    for src in [entry_source] + [os.path.join(repo, m) for m in PHYSICS_MODULES]:
        obj = os.path.join(out_dir, os.path.basename(src).replace(".s", ".o"))
        assemble(src, obj)
        objs.append(obj)
    elf = os.path.join(out_dir, "physics.elf")
    binary = os.path.join(out_dir, "physics.bin")
    _run([LD, "-T", os.path.join(repo, "physics.ld")] + objs + ["-o", elf])
    _run([OBJCOPY, "-O", "binary", elf, binary])
    return elf, binary


def write_pin(digest_hex, path):
    words = [digest_hex[i:i + 8] for i in range(0, 64, 8)]
    with open(path, "w") as f:
        f.write("/* Generated by m2_build.py: SHA-256 of the pinned physics.bin. */\n")
        f.write(f"/* {digest_hex} */\n")
        f.write("    .word " + ", ".join("0x" + w for w in words[:4]) + "\n")
        f.write("    .word " + ", ".join("0x" + w for w in words[4:]) + "\n")


def build_atlas(out_dir, physics_bin, repo=".", defsyms=None):
    """Build atlas_m2.bin into out_dir pinning physics_bin. defsyms override
    descriptor fields / entry ABI registers (hostile matrix only)."""
    repo = os.path.abspath(repo)
    out_dir = os.path.abspath(out_dir)
    os.makedirs(out_dir, exist_ok=True)
    write_pin(sha256_file(physics_bin), os.path.join(out_dir, "physics_pin.inc"))
    sha_obj = os.path.join(out_dir, "sha256_clean.o")
    _run([CC, "-nostdlib", "-ffreestanding", "-mgeneral-regs-only", "-O2", "-c",
          os.path.join(repo, "sha256_clean.c"), "-o", sha_obj])
    atlas_obj = os.path.join(out_dir, "atlas_m2.o")
    assemble(os.path.join(repo, "atlas_m2.s"), atlas_obj, defsyms=defsyms, cwd=out_dir)
    elf = os.path.join(out_dir, "atlas_m2.elf")
    binary = os.path.join(out_dir, "atlas_m2.bin")
    _run([LD, "-Ttext=0x00000000", atlas_obj, sha_obj, "-o", elf])
    _run([OBJCOPY, "-O", "binary", elf, binary])
    return elf, binary


def build_canonical(repo="."):
    """Build the canonical physics.bin, physics_pin.inc and atlas_m2.bin in
    the repository root (intermediates under build/canonical)."""
    repo = os.path.abspath(repo)
    work = os.path.join(repo, "build", "canonical")
    elf, built = build_physics(work, repo)
    physics_bin = os.path.join(repo, "physics.bin")
    with open(built, "rb") as src, open(physics_bin, "wb") as dst:
        dst.write(src.read())
    _, atlas_built = build_atlas(work, physics_bin, repo)
    with open(os.path.join(work, "physics_pin.inc")) as src, \
            open(os.path.join(repo, "physics_pin.inc"), "w") as dst:
        dst.write(src.read())
    with open(atlas_built, "rb") as src, open(os.path.join(repo, "atlas_m2.bin"), "wb") as dst:
        dst.write(src.read())
    return elf, physics_bin


if __name__ == "__main__":
    elf, physics_bin = build_canonical(".")
    print(f"physics.bin  {sha256_file(physics_bin)}")
    print(f"atlas_m2.bin {sha256_file('atlas_m2.bin')}")
